import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Hamid',
      email: 'helloheroemail@gmail.com',
      password: bcrypt.hashSync('555555'),
      isAdmin: true,
    },
    {
      name: 'Wife',
      email: 'wife@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Responsive Web Design',
      slug: 'responsive-web-design',
      category: 'Courses',
      image: '/images/programmer.jpg',
      price: 99,
      brand: 'Udemy',
      rating: 4.8,
      numReviews: 10,
      countInStock: 20,
      description: 'Awesome learning video for starter',
    },
    {
      name: 'Beginner Photography Course',
      slug: 'photography',
      category: 'Courses',
      image: '/images/photographer.jpg',
      price: 89,
      brand: 'Canon',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular course for photographer',
    },
    {
      name: 'Essential Cooking Skills',
      slug: 'cook',
      category: 'Courses',
      image: '/images/cook.jpg',
      price: 89,
      brand: 'Udemy',
      rating: 4.3,
      numReviews: 5,
      countInStock: 20,
      description: 'You can be a chef!',
    },
    {
      name: 'Mental Health Masters',
      slug: 'mental-health',
      category: 'Courses',
      image: '/images/mental health.jpg',
      price: 89,
      brand: 'Udemy',
      rating: 4.2,
      numReviews: 13,
      countInStock: 20,
      description: 'Improve mental & physical fitness',
    },
    {
      name: 'Networking Course',
      slug: 'networking',
      category: 'Courses',
      image: '/images/networking.jpg',
      price: 89,
      brand: 'Udemy',
      rating: 4.3,
      numReviews: 7,
      countInStock: 20,
      description: 'This course is part of the Business English Communication',
    },
    {
      name: 'Storytelling Course',
      slug: 'storytelling',
      category: 'Courses',
      image: '/images/storytelling.jpg',
      price: 69,
      brand: 'Udemy',
      rating: 4.0,
      numReviews: 14,
      countInStock: 20,
      description: 'Influencing Speaker',
    },
    {
      name: 'Career Development',
      slug: 'career-development',
      category: 'Courses',
      image: '/images/career.jpg',
      price: 69,
      brand: 'Udemy',
      rating: 4.0,
      numReviews: 14,
      countInStock: 20,
      description: 'Career Development and Life Goal Setting',
    },
    {
      name: 'Work Ethics',
      slug: 'work-ethics',
      category: 'Courses',
      image: '/images/ethic.jpg',
      price: 69,
      brand: 'Udemy',
      rating: 4.0,
      numReviews: 14,
      countInStock: 20,
      description: 'Work Ethics, Attitude and Personality',
    },
  ],
};

export default data;
